baseURL = "https://noauto-nolife.com/"
languageCode = "ja"
title = "自動化無しに生活無し"
theme = "beg/"
hasCJKLanguage = "true"
summaryLength = "200"


[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe= true

[params]
    Author = "S.Asahina"
    Comments = "ロボット開発、始めました"
