baseURL = "https://noauto-nolife.com/"
languageCode = "ja"
title = "自動化無しに生活無し"
theme = "/beg/"
hasCJKLanguage = "true"
summaryLength = "200"
author = "Seiya Asahina"

googleAnalytics = "UA-102565734-2"

