baseURL = "https://noauto-nolife.com/"
languageCode = "ja"
title = "自動化無しに生活無し"
theme = "beg"
hasCJKLanguage = "true"
summaryLength = "200"

[params]
    Author = "S.Asahina"
    Comments = "We are not your kind."


